const SET_SCHOOLS = 'SET_SCHOOLS';
const SET_STUDENTS = 'SET_STUDENTS';
const CREATE_STUDENT = 'CREATE_STUDENT';
const UPDATE_STUDENT = 'UPDATE_STUDENT';
const DESTROY_STUDENT = 'DESTROY_STUDENT';
const SET_ERROR = 'SET_ERROR';

export {
    SET_SCHOOLS,
    SET_STUDENTS,
    CREATE_STUDENT,
    UPDATE_STUDENT,
    DESTROY_STUDENT,
    SET_ERROR
  };

